### ISSUE TITLE
AppImage crashes with error: undefined symbol: pango_coverage_get_type

### ISSUE THREAD

**Issue by makeworld-the-better-one** [gridsync/gridsync#487]
Hello, I'm trying out gridsync with the public test grid, and getting some crashes before I can begin uploading any files. I'm running the latest (0.5.0) AppImage on Arch Linux.

Here are the logs, obtained just by running `./Gridsync-Linux.AppImage` in the terminal:

```
/usr/lib/gvfs/libgvfscommon.so: undefined symbol: g_task_set_name
Failed to load module: /usr/lib64/gio/modules/libgvfsdbus.so
libpng warning: iCCP: profile 'icc': 0h: PCS illuminant is not D50
libpng warning: iCCP: profile 'icc': 0h: PCS illuminant is not D50
Fontconfig warning: "/usr/share/fontconfig/conf.avail/05-reset-dirs-sample.conf", line 6: unknown element "reset-dirs"
libpng warning: iCCP: profile 'icc': 0h: PCS illuminant is not D50
libpng warning: iCCP: profile 'icc': 0h: PCS illuminant is not D50
libpng warning: iCCP: profile 'icc': 0h: PCS illuminant is not D50
libpng warning: iCCP: profile 'icc': 0h: PCS illuminant is not D50
libpng warning: iCCP: profile 'icc': 0h: PCS illuminant is not D50
libpng warning: iCCP: profile 'icc': 0h: PCS illuminant is not D50
qt.qpa.xcb: QXcbConnection: XCB error: 3 (BadWindow), sequence: 1345, resource id: 13028294, major code: 40 (TranslateCoords), minor code: 0
/usr/lib/gvfs/libgvfscommon.so: undefined symbol: g_task_set_name
Failed to load module: /usr/lib64/gio/modules/libgioremote-volume-monitor.so
/usr/lib/gvfs/libgvfscommon.so: undefined symbol: g_task_set_name
Failed to load module: /usr/lib64/gio/modules/libgvfsdbus.so
/usr/lib/gvfs/libgvfscommon.so: undefined symbol: g_task_set_name
Failed to load module: /usr/lib64/gio/modules/libgioremote-volume-monitor.so

(gridsync:28223): Gtk-WARNING **: 13:28:04.046: Could not load a pixbuf from icon theme.
This may indicate that pixbuf loaders or the mime database could not be found.
**
Gtk:ERROR:gtkiconhelper.c:494:ensure_surface_for_gicon: assertion failed (error == NULL): Failed to load /usr/share/icons/breeze-dark/status/16/image-missing.svg: Unable to load image-loading module: /usr/lib/gdk-pixbuf-2.0/2.10.0/loaders/libpixbufloader-svg.so: /usr/lib/librsvg-2.so.2: undefined symbol: pango_coverage_get_type (gdk-pixbuf-error-quark, 5)
[1]    28215 IOT instruction (core dumped)  ./Gridsync-Linux.AppImage
```

I assume it's only that last log line that is relevant to the crash:

```
Gtk:ERROR:gtkiconhelper.c:494:ensure_surface_for_gicon: assertion failed (error == NULL): Failed to load /usr/share/icons/breeze-dark/status/16/image-missing.svg: Unable to load image-loading module: /usr/lib/gdk-pixbuf-2.0/2.10.0/loaders/libpixbufloader-svg.so: /usr/lib/librsvg-2.so.2: undefined symbol: pango_coverage_get_type (gdk-pixbuf-error-quark, 5)
```

To me this seems like some sort of software library versioning issue. I'm running fully updated Arch Linux, which has very recent software. Maybe the AppImage is trying to use some system library that is newer that it is expecting, causing the missing symbol? I would've thought AppImage packaging would bundle all these libraries, but maybe that's not how it works.

My gdk-pixbuf version is 2.42.8, if that helps. Let me know if there's any other info I can provide.

**Comment by makeworld-the-better-one** [comment]
I have been unable to build from source on the latest commit XXX due to the error below, so unfortunately I can't test if that would solve the problem.

```
-- Deploying executables -- 
ERROR: No such file or directory:  build/AppDir/usr/bin/gridsync 
Traceback (most recent call last):
  File "<redacted>/gridsync/scripts/make_appimage.py", line 79, in <module>
    os.chmod(glob.glob('build/AppDir/usr/lib/libpython*.so.*')[0], 0o755)
IndexError: list index out of range
```

**Comment by crwood** [comment]
Hey there! Thanks for the report -- and for providing all of these details! :)

Shipping highly-portable binaries for GNU/Linux is _hard_ -- doubly so for Python applications (where there is no common/official tooling for "compiling" packages for end-user-facing/desktop targets -- and, maybe, _triply_ so for Arch Linux targets in particular, where everything is cutting-edge and any two given Arch installs/setups can differ so radically from one another)...

Anyway, to try and get to the root of _this_ issue: Generally speaking, both PyInstaller/AppImage binaries have strong forward-compatibility but weak backward-compatibility guarantees such that both projects [recommend](https://pyinstaller.org/en/stable/usage.html#making-gnu-linux-apps-forward-compatible) [building](https://docs.appimage.org/reference/best-practices.html#binaries-compiled-on-old-enough-base-system) applications on as old of a system as you can support. In the case of Gridsync, GNU/Linux binaries are built under [a CentOS 7 environment](https://github.com/gridsync/gridsync/blob/624f11e861bef1c733f618fc15eb667a61a7791e/Containerfile.qt5#L1=) since it's the "oldest" GNU/Linux distribution (as measured by its extremely low [glibc version](https://pkgs.org/search/?q=glibc)) that still receives security updates. Nevertheless, even with these measures in place, we've seen a number of library-compatibility ("undefined symbol") issues like these over the years. Here are a few of them, if you're interested: https://github.com/gridsync/gridsync/issues/43 https://github.com/gridsync/gridsync/issues/47 https://github.com/gridsync/gridsync/issues/189

In previous instances, resolving the problem involved a) identifying the library in the PyInstaller/AppImage bundle that was causing the issue and b) [removing/excluding](https://github.com/gridsync/gridsync/blob/624f11e861bef1c733f618fc15eb667a61a7791e/pyinstaller.spec#L335-L337=) that library from the PyInstaller/AppImage package. Doing this effectively forces the application to "fall back" to using whatever library version is already installed on your local system rather than using the one that's included in the bundle (which, as per the above, is probably much older than -- and may be incompatible with -- other components on your system). The AppImage project already maintains a [rather extensive "excludelist"](https://github.com/AppImage/pkg2appimage/blob/master/excludelist) of such problematic libraries, and, as I can see from their [latest commit](https://github.com/AppImage/pkg2appimage/commit/f2df956789f36204213876c96500c8b05595e43b), libpango was _just_ added to the exclude list. Given the error message that you saw ("undefined symbol: pango_coverage_get_type"), I wonder now whether that change will be sufficient to fix the problem...

Here's one way to try and find out:
1. Extract the contents of the Gridsync AppImage to your local filesystem: `./Gridsync.AppImage --appimage-extract`
2. Remove (or rename) the potentially-offending pango-related libraries: `rm ./squashfs-root/usr/bin/libpango*.so.*`                         
3. Try launching the (extracted) application: `./squashfs-root/AppRun`

If the application launches without issue (or, I guess, without _this_ specific error message) then, I think, we can be pretty confident that excluding libpango is a good idea. If that didn't help, or if the error persists, some other library -- or set of libraries -- maybe be at fault here (in which case we should try to investigate further).

**Comment by crwood** [comment]
If you're interested in testing a build that excludes `libpango-1.0.so.0`, `libpangocairo-1.0.so.0`, and `libpangoft2-1.0.so.0` (without having to follow the steps above), here are some fresh artifacts: https://github.com/gridsync/gridsync/actions/runs/2504335195

**Comment by makeworld-the-better-one** [comment]
Thanks for looking into this! I tried the build you've linked (specifically `Gridsync-ubuntu-22.04-pyqt5.AppImage `) and it appears to have fixed the issue! I was able to add a folder to the public test grid which I couldn't do before, clicking the Folder button is what would cause the crash.

Unfortunately when syncing the folder I got another crash. I assume this is a different issue but I thought I'd put it here in case:

```
Traceback (most recent call last):
  File "twisted/internet/defer.py", line 1660, in _inlineCallbacks
StopIteration: [{'relpath': 'test.bin', 'mtime': 1655386477, 'last-updated': 1655386492, 'last-upload-duration': None, 'size': 4096, 'path': '/home/makeworld/tmp/gridsync-tmp/test.bin'}]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "twisted/internet/defer.py", line 1660, in _inlineCallbacks
StopIteration: [{'relpath': 'test.bin', 'mtime': 1655386477, 'last-updated': 1655386492, 'last-upload-duration': None, 'size': 4096, 'path': '/home/makeworld/tmp/gridsync-tmp/test.bin'}]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "twisted/internet/defer.py", line 1660, in _inlineCallbacks
StopIteration: ('gridsync-tmp', [{'relpath': 'test.bin', 'mtime': 1655386477, 'last-updated': 1655386492, 'last-upload-duration': None, 'size': 4096, 'path': '/home/makeworld/tmp/gridsync-tmp/test.bin'}])

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "gridsync/gui/usage.py", line 406, in on_total_folders_size_updated
  File "gridsync/gui/usage.py", line 330, in _update_info_label
TypeError: converted_batch_size() missing 1 required positional argument: 'value'
[1]    137184 IOT instruction (core dumped)  ./Gridsync-no-pango.AppImage
```

When I manually removed the pango libs from the 0.5.0 AppImage, everything worked great and I was able to sync the same folder that caused the crash above. So in my book this is fixed, and the crash above is an unrelated bug. Thanks for all the help!

Let me know if you'd like me to open a new issue with the crash log above.

**Comment by crwood** [comment]
>Thanks for looking into this! I tried the build you've linked (specifically Gridsync-ubuntu-22.04-pyqt5.AppImage ) and it appears to have fixed the issue! 

Great! Thank you so much for confirming the fix! I'll merge it into `master` as soon as https://github.com/gridsync/gridsync/pull/488 passes CI...

The other issue you've discovered is a very recent regression (introduced by https://github.com/gridsync/gridsync/pull/477) that has already been [fixed](https://github.com/gridsync/gridsync/commit/4f1cb2001eab2a5c9f58620a3194e360d37496cf) in a separate branch. I will split/cherrypick that commit out into a separate PR shortly so that it's in `master` too. I've already taken the liberty of [filing an Issue for it]() -- but thanks for offering (and thanks, again, for both reports and for confirming the fix)!
